language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t blueskyzhy/multi-docker -f ./client/Dockerfile.dev ./client
#  - docker build myotherproject

#command to run the test suite, 
#and if not exit(0) then it would assume fail
script:
  - docker run -e CI=true blueskyzhy/multi-docker npm run test
#  - docker run myotherproject runmytests

after_success:
  - docker build -t blueskyzhy/multi-client ./client
  - docker build -t blueskyzhy/multi-nginx ./nginx
  - docker build -t blueskyzhy/multi-server ./server
  - docker build -t blueskyzhy/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push blueskyzhy/multi-client
  - docker push blueskyzhy/multi-nginx
  - docker push blueskyzhy/multi-server
  - docker push blueskyzhy/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  app: "DockerReact"
#  evn: "Dockerreact-env"
#  bucket_name: "elasticbeanstalk-us-west-2-683938102574"
#  bucket_path: "DockerReact"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY